services:
  db:
    image: mysql:8.0.35
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_app
    restart: unless-stopped
    depends_on:
      - db
      - mailhog
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: "define('WP_ENVIRONMENT_TYPE', 'local');"
    volumes:
      - ./src:/var/www/html
    networks:
      - wordpress_net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: wordpress_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
